### ISSUE TITLE
Screenshot don't work

### ISSUE THREAD

**Issue by 2803media** [RafalWilinski/serverless-puppeteer-layers#3]
Finally the installation works like a charm:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (1.7 MB)...
Serverless: Uploading service .zip file to S3 (45.35 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.................................
Serverless: Stack update finished...
Service Information
service: serverless-puppeteer-layers
stage: dev
region: eu-central-1
stack: serverless-puppeteer-layers-dev
api keys:
  None
endpoints:
  GET - <DEPLOYED_ENDPOINT>
functions:
  puppeteer-orchestrator: serverless-puppeteer-layers-dev-puppeteer-orchestrator
layers:
  chrome: arn:aws:lambda:eu-central-1:0682994076:layer:chrome:5
Serverless: Setting up content handling in AWS API Gateway (takes ~1 min)...
```

But the screenshot function doesn't work like expected because the image is not displayed, do I miss something?

```<DEPLOYED_ENDPOINT>?address=https://google.com```

But the base64 image is good, I check with a base64 decoder!
